### ISSUE TITLE
scale_stats.npy missing

### ISSUE THREAD

**Issue by ADD-eNavarro** [hamedhemati/SpeakerEncoder#1]
Hello.
I am trying your code, but I get an exception in audio.py -> load_stats, first line, when loading stats_path it's looking for the file in the title, but it's not there.

**Comment by HamedHemati** [comment]
Hi!
Did you download the checkpoint from the right link?
I just tested on the one from below and it works for me:
https://drive.google.com/drive/folders/15oeBYf6Qn1edONkVLXe82MzdIi3O_9m3

Please pull the latest version of the repository and run the code after copying the downloaded files to the pretrained_model folder as explained on the README page.
